/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school.system;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DANIEL
 */
public class StudentsRecords extends javax.swing.JFrame {
     //declaring static variables
    private static final String username="root";
    private static final String password="";
    private static final String url="jdbc:mysql://localhost:3306/school";
    
    //sql statement variables
    Connection sqlConn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    int q,i,deleteItem;
    public static int id;
    
    
    

    /**
     * Creates new form Records
     */
    public StudentsRecords() {
        initComponents();
        updateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        updateBtn8 = new javax.swing.JButton();
        deleteBtn8 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jtableData = new javax.swing.JTable();
        addstudentBtn8 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        printBtn8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student's Records");

        jPanel13.setBackground(new java.awt.Color(0, 255, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 51), new java.awt.Color(0, 255, 0)));
        jPanel13.setForeground(new java.awt.Color(0, 0, 255));

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 33)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Student's Information & Records");

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setForeground(new java.awt.Color(0, 0, 204));

        txtSearch.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        updateBtn8.setBackground(new java.awt.Color(0, 204, 204));
        updateBtn8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        updateBtn8.setForeground(new java.awt.Color(0, 153, 51));
        updateBtn8.setText("Update");
        updateBtn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn8.setBackground(new java.awt.Color(255, 51, 51));
        deleteBtn8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        deleteBtn8.setForeground(new java.awt.Color(0, 255, 255));
        deleteBtn8.setText("Delete");
        deleteBtn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jtableData.setAutoCreateRowSorter(true);
        jtableData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204), 3));
        jtableData.setFont(new java.awt.Font("sansserif", 0, 19)); // NOI18N
        jtableData.setForeground(new java.awt.Color(0, 51, 255));
        jtableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Id", "Reg_No", "Name", "Age", "Gender", "Parent", "Phone", "Date Admited"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtableData.setRowHeight(30);
        jtableData.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtableData.setShowGrid(false);
        jtableData.setShowHorizontalLines(true);
        jtableData.setShowVerticalLines(true);
        jtableData.getTableHeader().setReorderingAllowed(false);
        jtableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableDataMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jtableData);
        if (jtableData.getColumnModel().getColumnCount() > 0) {
            jtableData.getColumnModel().getColumn(0).setMinWidth(20);
            jtableData.getColumnModel().getColumn(0).setMaxWidth(40);
            jtableData.getColumnModel().getColumn(1).setMinWidth(20);
            jtableData.getColumnModel().getColumn(1).setMaxWidth(40);
            jtableData.getColumnModel().getColumn(4).setMinWidth(20);
            jtableData.getColumnModel().getColumn(4).setMaxWidth(40);
            jtableData.getColumnModel().getColumn(5).setMaxWidth(350);
        }

        addstudentBtn8.setBackground(new java.awt.Color(255, 255, 0));
        addstudentBtn8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        addstudentBtn8.setForeground(new java.awt.Color(0, 0, 204));
        addstudentBtn8.setText("Add Student");
        addstudentBtn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addstudentBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentBtnActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel13.setText("Search:");

        printBtn8.setBackground(new java.awt.Color(51, 153, 255));
        printBtn8.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        printBtn8.setText("Print");
        printBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(updateBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addstudentBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addComponent(jScrollPane9)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(printBtn8))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addstudentBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:
        //code for printing the students records
        MessageFormat header = new MessageFormat("Printing In Progress");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");

        try{
            jtableData.print(JTable.PrintMode.NORMAL, header, footer);

        }catch(java.awt.print.PrinterException ex){
            JOptionPane.showMessageDialog(null, ex, "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void addstudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentBtnActionPerformed
        // event to add student
        Students st=new Students();
        st.show();
        st.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addstudentBtnActionPerformed

    private void jtableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableDataMouseClicked

        //mouse click event
        DefaultTableModel RecordTable = (DefaultTableModel) jtableData.getModel();
        int selectedRow = jtableData.getSelectedRow();
    }//GEN-LAST:event_jtableDataMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        //code for deleting record from the table
        //calling the database connection
        connectDb();

        //here we delete the record

        TableModel model = jtableData.getModel();
        int selectedRow = jtableData.getSelectedRow();
        id = (int) model.getValueAt(selectedRow, 1);

        if(selectedRow == -1){
            JOptionPane.showMessageDialog(null, "Please Select a Record to delete",
                "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            System.err.print(id);
            int confirmDelete = JOptionPane.showConfirmDialog(null, "Delete this Record?",
                "Warning",JOptionPane.YES_NO_OPTION);
            if(confirmDelete == JOptionPane.YES_OPTION){
                try{
                    pst=sqlConn.prepareStatement("DELETE FROM student WHERE id=?");

                    pst.setInt(1, id);
                    pst.executeUpdate();
                    updateDB();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex, "Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        //calling function to set fields
        setTextFields();
        System.out.print(getId());
    }//GEN-LAST:event_updateBtnActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String searchString = txtSearch.getText();
        serachRecord(searchString);
    }//GEN-LAST:event_txtSearchKeyReleased
    
    //databae connection method
    public void connectDb(){
        try{
            sqlConn=DriverManager.getConnection(url,username,password);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    //function to auto update jtable on insertion or update
    public void updateDB(){
        //calling database connection
        connectDb();
        
        //fetchig data from the database tables of students
        try{
            pst = sqlConn.prepareStatement("SELECT * FROM student");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = (ResultSetMetaData) rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel) jtableData.getModel();
            RecordTable.setRowCount(0);
            int sno = 1;
            
            
            
            while(rs.next()){
                Vector columnData = new Vector();
                
                for(i=1;i<=q;i++){                    
                    columnData.add(sno);
                    columnData.add(rs.getInt("id"));
                    columnData.add(rs.getString("regno"));
                    columnData.add(rs.getString("name"));
                    columnData.add(rs.getString("age"));
                    columnData.add(rs.getString("gender"));
                    columnData.add(rs.getString("parent"));
                    columnData.add(rs.getString("phone"));
                    columnData.add(rs.getString("date_reg"));
                }
                sno += 1;
                RecordTable.addRow(columnData);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    //method to set fields in the text fieldss
    public void setTextFields(){
        // event to add student
        Students st = new Students();
        
        TableModel model = jtableData.getModel();
        int selectedRow = jtableData.getSelectedRow();
        
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(null, "Please Select a Record To Update!!","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            //displaying the original form for update
           st.show();
           st.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           
           //getting the values at the jframe rows
           id = (int) model.getValueAt(selectedRow, 1);
           String newRegno = model.getValueAt(selectedRow, 2).toString();
           String newName = model.getValueAt(selectedRow, 3).toString();
           String newAge = model.getValueAt(selectedRow,4).toString();
           String newGender = model.getValueAt(selectedRow, 5).toString();
           String newParent = model.getValueAt(selectedRow, 6).toString();
           String newPhone = model.getValueAt(selectedRow, 7).toString();
           
           
           //setting the values gotten form the table into jtextfields
           st.jregno.setText(newRegno);
           st.jname.setText(newName);
           st.jage.setText(newAge);
           st.jgender.setSelectedItem(newGender);
           st.jparent.setText(newParent);
           st.jphone.setText(newPhone);           
        }
    }    
    //method to get the value of the id of selected row to allow access outside the class
    public int getId(){
        return id;
    } 
    
    //method for searching record in the database
    public void serachRecord(String searchStr){
        TableModel model = jtableData.getModel();
        TableRowSorter<DefaultTableModel> myStr = new TableRowSorter<DefaultTableModel>((DefaultTableModel) model);
        jtableData.setRowSorter(myStr);
        myStr.setRowFilter(RowFilter.regexFilter(searchStr));
    }
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addstudentBtn8;
    private javax.swing.JButton deleteBtn8;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTable jtableData;
    private javax.swing.JButton printBtn8;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JButton updateBtn8;
    // End of variables declaration//GEN-END:variables

}
